version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - backend
    restart: unless-stopped
  
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - backend
    restart: unless-stopped

  redis:
    container_name: redis_container
    image: redis
    volumes:
      - redis:/data
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    networks:
      - backend

  ssoserver:
    build: 
      context: sso-server
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgres:5432
      PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
      - "postgres"

networks:
  backend:
    driver: bridge

volumes:
    postgres: 
    pgadmin: 
    redis: