"""make username unique

Revision ID: 560b66ad171f
Revises: 18bd027b4740
Create Date: 2023-11-04 18:13:18.739592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '560b66ad171f'
down_revision: Union[str, None] = '18bd027b4740'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'Profile', ['user_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Profile', type_='unique')
    # ### end Alembic commands ###
